### ISSUE TITLE
Issue installing requirements.txt upon bootstrap

### ISSUE THREAD

**Issue by jmithani** [nprapps/dailygraphics#259] opened 2018-01-10 22:52 UTC
```
$ pip install -r requirements.text
Collecting Authomatic==0.1.0.post1 (from -r requirements.txt (line 1))
  Downloading Authomatic-0.1.0.post1.tar.gz (864kB)
    100% |████████████████████████████████| 870kB 1.4MB/s
Collecting Fabric==1.4.3 (from -r requirements.txt (line 2))
  Downloading Fabric-1.4.3.tar.gz (221kB)
    100% |████████████████████████████████| 225kB 4.5MB/s
Collecting Flask==0.9 (from -r requirements.txt (line 3))
  Downloading Flask-0.9.tar.gz (481kB)
    100% |████████████████████████████████| 491kB 2.7MB/s
Collecting Jinja2==2.9.5 (from -r requirements.txt (line 4))
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 4.5MB/s
Collecting Werkzeug==0.8.3 (from -r requirements.txt (line 5))
  Downloading Werkzeug-0.8.3.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 1.2MB/s
Collecting awscli==1.11.61 (from -r requirements.txt (line 6))
  Downloading awscli-1.11.61-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 1.2MB/s
Collecting bcdoc==0.12.0 (from -r requirements.txt (line 7))
  Downloading bcdoc-0.12.0.tar.gz
Collecting boto==2.25.0 (from -r requirements.txt (line 8))
  Downloading boto-2.25.0-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 1.2MB/s
Collecting copytext==0.1.9 (from -r requirements.txt (line 9))
  Downloading copytext-0.1.9.tar.gz
Collecting cssmin==0.1.4 (from -r requirements.txt (line 10))
  Downloading cssmin-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.10.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-affzwp/cssmin/setup.py", line 7, in <module>
        from distribute_setup import use_setuptools; use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-affzwp/cssmin/
```
Reproducible by @ghing.

**Comment by ghing** [comment] 2018-01-10 22:56
This appears to be a result of [this issue](https://stackoverflow.com/questions/46967488/getting-error-403-while-installing-package-with-pip/46979531), which I found mentioned in [this StackOverflow question](https://stackoverflow.com/questions/46967488/getting-error-403-while-installing-package-with-pip/46979531). I'm trying out a few things to find a suggested fix.

**Comment by jmithani** [comment] 2018-01-10 22:58
Relevant: https://github.com/zacharyvoase/cssmin/pull/5

**Comment by jmithani** [comment] 2018-01-10 22:59
@ghing both hyperlinks head to the StackOverflow question

**Comment by ghing** [comment] 2018-01-10 23:01
@jmithani, edited to fix the link. And yeah, zacharyvoase/cssmin#5 is relevant.

**Comment by ghing** [comment] 2018-01-10 23:14
So the problem is that version 0.1.4 of `cssmin` (the version in `requirements.txt`) downloads `distribute` from `http://pypi.python.org/packages/source/d/distribute/` when installing `cssmin`.

See https://github.com/zacharyvoase/cssmin/blob/v0.1.4/distribute_setup.py#L131.

However, PyPI no longer supports non-SSL URLs. See the [mailing list post I referenced earlier](https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html).

Here's a workaround to try:

Edit requirements.txt so it installs the newer version of cssmin (0.2.0).  It should look like this:

```
Authomatic==0.1.0.post1
Fabric==1.4.3
Flask==0.9
Jinja2==2.9.5
Werkzeug==0.8.3
awscli==1.11.61
bcdoc==0.12.0
boto==2.25.0
copytext==0.1.9
cssmin==0.2.0
docutils==0.11
gunicorn==19.1.1
nose==1.2.1
odict==1.5.1
openpyxl==2.0.3
ply==3.4
pycrypto==2.6
requests==1.1.0
rsa==3.1.2
sauceclient==0.2.1
selenium==3.3.1
slimit==0.7.4
ssh==1.7.14
wsgiref==0.1.2
xlrd==0.9.0
smartypants==1.8.6
```

Then try to reinstall the dependencies:

```
pip install -r requirements.txt
```

If, after some testing, the rig seems to work as expected, this fix to `requirements.txt` should be made permanent. I didn't want to commit it right away since there's the small possibility that there is some kind of breaking change between version 0.1.4 and 0.2.0.

I confirmed that this workaround at least allows the python dependencies to be installed, lets me run `fab app` and lets me view a graphic in the local development server.  However I have *not* tested that CSS minification works correctly.

**Comment by ghing** [comment] 2018-01-10 23:17
I made a backup of an old CSS file generated from a graphic, `graphic-header.css.bak` and then ran `fab render` to regenerate `graphic-header.css`.  `fab render` ran without error, which means that minification isn't totally broken. However, when I ran `diff` on the files, the command reported some differences. So, further testing and/or research should be done to make sure the update to `cssmin` doesn't break anything important.

**Comment by ghing** [comment] 2018-01-10 23:18
I'm assigning this to @jjelosua because I probably won't get to fully testing the implications of a `cssmin` upgrade before I leave.

**Comment by jjelosua** [comment] 2018-01-11 22:16
@ghing can you tell me which old graphic have you used to check the diffing....I have done that for an old graphic `worm-soil-20160811`  and the diffing resulted in identical files.

**Comment by jjelosua** [comment] 2018-01-11 22:28
Taking a look at the commits from our original version of `cssmin 0.1.4` to `cssmin 0.2.0` the changes do not touch the minification functionality and are in fact removing the `distribute_setup.py` in favor of `setuptools` (https://github.com/zacharyvoase/cssmin/commit/ae2a4fa14a067544e6a4bf098a939c0d0ac49d8d) so I think it is safe to upgrade to 0.2.0 but waiting to hear from the diff case that Geoff mentioned

**Comment by ghing** [comment] 2018-01-12 18:11
@jjelosua, the graphic I did a quick test on was `slingshot-sketch-20171206`.  It's possible that the css that was in my directory that I tested was stale. If the minification code wasn't touched in the update to 0.2.0, I think it's probably fine to make my fix permanent.

**Closed** 2018-01-12 19:35 UTC
